---
# https://realpython.com/intro-to-pyenv/
- name: Install Ebidlocal Watch list
  hosts: alt-server

  vars_files:
    - vars.yml

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www/ebidlocal
        state: directory
        owner: ebidlocal
        group: dev
        mode: '0755'

    - name: Git checkout
      ansible.builtin.git:
        repo: https://github.com/scirelli/auction-ebidlocal-search
        dest: /home/ebidlocal/Projects/
        update: true

    - name: Run 'build' target
      make:
        chdir: /home/ebidlocal/Projects/auction-ebidlocal-search
        target: build

    - name: Reload the Web service
      ansible.builtin.systemd:
        name: watchlist-http.service
        state: reloaded

    - name: Reload the scanner
      ansible.builtin.systemd:
        name: watchlist-scanner.service
        state: reloaded
